### ISSUE TITLE
Basic initial pattern to confirm functionality when initially loaded 

### ISSUE THREAD

**Issue by 01GOD** [copych/ESP32_Open303#1]
Thanks for posting that! Should add a basic initial sequence in the sequencer so it does something to confirm functionality when initially loaded. 

I tried adding this to the loop() in the main .ino, but it simply output a distorted sounding long note: 
`Synth.noteOn(50, 120, 1.0f);`

I guess I could add more notes and put a delay call between those to make a sequence until I wade through the sequencer code, but it would be appreciated if there is an initial sequence playing to confirm proper functionality and pin config and so on.

**Comment by copych** [comment]
I'll think of this trial pattern.

**Comment by 01GOD** [comment]
A simple sequence of middle C with note off in between each is a start. That way it doesn't show favoritism for any of the random button pushers of history. LOL. 

Can alternate accents on. And if want to showcase slides, can do a couple of lowest note sliding to highest note and back to middle note patterns in that main pattern.

**Comment by copych** [comment]
When I faced testing issues with AcidBox , I've finally added AcidBanger ))

**Comment by 01GOD** [comment]
> When I faced testing issues with AcidBox , I've finally added AcidBanger ))

Ah. Guess that does make it easier to confirm functionality.

**Comment by copych** [comment]
Acidbanger included

**Comment by 01GOD** [comment]
> Acidbanger included

Thanks! Plan to try that on a board today.
